# Generated by Django 5.2.9 on 2026-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=200, unique=True)),
                ('best_champ', models.CharField(max_length=50)),
                ('best_champ_winrate', models.IntegerField()),
                ('champ_img_route', models.TextField()),
                ('win_kda', models.FloatField()),
                ('lose_kda', models.FloatField()),
                ('kda_tips', models.JSONField()),
                ('jngl_objectives', models.JSONField()),
                ('sorted_jngl_objectives', models.JSONField()),
                ('average_ward_wins', models.FloatField()),
                ('average_ward_loses', models.FloatField()),
                ('warding_tips', models.JSONField()),
                ('win_by_game_length', models.JSONField()),
                ('game_length_tips', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
